### PR TITLE
Quote useralias when using email

### PR DESCRIPTION
**Pull request by nfg**
For issue #53.

### CODE REVIEW

**Comment by nfg** [comment]
Hey! I updated this based off your feedback in #53. Now it'll escape display-name in the bit of code that generates the From: header. What do you think?

**Comment by nfg** [comment]
... And sorry for force-pushing a second time; I accidentally used my work email in my git commit, which is a no-no. I think it should be good now. Fingers crossed!

**Comment by kootenpv** [comment]
No worries about a wrong commit, glad you sorted it out.

I'm actually not sure we want to always quote it, shouldn't we only quote it when there is a `@` in it like you mentioned in the spec? I like the addition of checking for existing quotes. Let me know if it would indeed be better to always quote; I'd merge it shortly thereafter.

**Comment by nfg** [comment]
I dunno, it's your package. :smiley: 

OK. I looked at RFC 5322 again. Inside a quote-string you can include any ASCII, except for / and " which must be properly quoted. Inside an email address you're allowed any ASCII except for the special characters, which are

```
   specials        =   "(" / ")" /        ; Special characters that do
                       "<" / ">" /        ;  not appear in atext
                       "[" / "]" /
                       ":" / ";" /
                       "@" / "\" /
                       "," / "." /
                       DQUOTE
```

So, OK, how about this case:

```python
yag = yagmail.SMTP(
    user={ 'nigelsezyarr@WORK.com': 'holla (zug)\\"yarr' },
    host='mail.WORK.com', password=None, smtp_skip_login=True)
```

Brackets, backslashes, quotation marks are all verboten, but can be included in quoted-string.

(And actually, for that particular case, we need to add *another* replace statement for the backslash character. I have another commit coming...)

I think it'd be reasonable for people to have a display name like "Bob (@work)", which will need to be escaped. Rather than figure out if a display name needs to be escaped, it'd be easier to escape automatically.

**Comment by nfg** [comment]
Hey! Is there anything you'd like me to change?

**Comment by kootenpv** [comment]
Thanks! Somehow it missed my attention, my apologies.

**Comment by nfg** [comment]
No worries! These things happen. :) Thank you!

**Pull request merged**
