### PR TITLE
add context management for SMTP server

### PR DESCRIPTION
**Pull request by jrkerns**
so we can do things like:

    with yagmail.SMTP(...) as yagserver:
        yagserver.send(...)

just as the real SMTP class has.

### CODE REVIEW

**Comment by kootenpv** [comment]
Nice one :) I just added a cleanup on delete, but this is even nicer.

**Comment by kootenpv** [comment]
Should merge before closing...

**Comment by kootenpv** [comment]
It worked succesfully, but then it was closed, reopened and now the build does not pass. Very strange, but thanks a lot, context manager is a very good idea :)

**Comment by jrkerns** [comment]
Hmm. Well, it was the thought that counted, right? =)

**Comment by kootenpv** [comment]
@jrkerns In case it wasn't clear -- it has been merged anyway since the build is successful (though it doesn't show here). Thanks :)

**Comment by jrkerns** [comment]
Oh, okay. Good project, keep it up!

**Pull request merged**
