### PR TITLE
Add basic Sphinx documentation

### PR DESCRIPTION
**Pull request by Volcyy**
Your roadmap listed `Add documentation to all functions (high, halfway)`. This PR adds a basic API reference that can be built with Sphinx. I hope this is what you had in mind with it.

I've also tried adding it on readthedocs earlier today without any issues, it looks just like when using it locally (as expected).

I changed some of the docstrings where it messed up the formatting, but didn't add anything beyond that. I can also try to add documentation for parameters or similar things, but I'm not too informed about the inner workings of the library, specifically usage of some attributes.

Generating documentation is done through using `make html` in the `docs` subdirectory. Sphinx needs to be installed (`pip3 install sphinx`).

One thing to note is that I chose your GitHub name as the author name. Tell me if I should change that, I had to set it to something in `conf.py`.

Another thing, it's possible to customize the documentation (e.g. adding a logo) through `html_theme_options` in `conf.py`, see [Customizing - Alabaster documentation](http://alabaster.readthedocs.io/en/latest/customization.html#theme-options). For example, one could use the [logo from the README](https://github.com/kootenpv/yagmail/blob/master/resources/icon.png) as the project icon. Let me know if I should add this.

If I should change, add, or remove anything, let me know. Thank you for this package!

### CODE REVIEW

**Comment by JelaniThompson** [comment]
@Volcyy Lookin' good

**Comment by kootenpv** [comment]
Wow, very nice! I'm never been the biggest fan of readthedocs, but you've done a great job. I'm very happy to accept the pull request, and agree with the idea of adding the icon. It makes a nice start for me to give readthedocs a try :) The `conf.py` decision is fine with me.

Also, I'm most likely open to more suggestions (that customization page has a lot of options!). So feel free adding more sensible changes :)!

Would you like for me to include it as it is right now, or would you prefer to wait for more additions?

Thank you so much for your effort!

Kind regards,
Pascal

**Comment by Volcyy** [comment]
Thanks for the positive feedback! I'll get the icon in and see what else I can try out.

**Comment by Volcyy** [comment]
Alright, I added the icon as well as a short description below it, and a GitHub button showing the total stars. I can't think of any further customization, then again I'm somewhat uncreative 🤔
I hope this is as you expected it 😄 
If I think of anything else, I'll open another PR.

**Comment by kootenpv** [comment]
Fantastic! Thanks a lot :) I'll include it. What is the obvious way to "deploy" Sphinx documentation (if I can make use of your expertise)?

**Comment by Volcyy** [comment]
I think you can use GitHub Pages but what I usually see for Python projects is Read the Docs since it integrates very nicely with Sphinx, and you can imagine it like "continuous documentation" - if you push an update, the documentation will update too.
If you don't already have an account, you can [sign up here](https://readthedocs.org/accounts/signup/). Afterwards (if you don't need to go through some confirmation process), you should be redirected to your dashboard, where you can import a project. You may need to click the refresh button. After you found yagmail in the list, click the plus to add the project. You can configure the documentation there as you wish, although the defaults are probably okay.
Now the documentation should build at `yagmail.readthedocs.io`, if nothing went wrong. The default interpreter is 2.7, you might want to change that in the advanced project settings (Administration -> Advanced Settings -> Python Interpreter).

Hope that helps!

**Comment by kootenpv** [comment]
Thanks a lot! http://yagmail.readthedocs.io has arrived :-)

**Pull request merged**
